name: Standard Go Test

on:
  workflow_call:

jobs:
  standard-go-test:
    name: go${{ matrix.go-version }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - "1.16.x"
          - "1.17.x"
          - "1.18.x"
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: 0
        run: |
          go test -v -race -tags "sqlite,integration" ./...
